"""Safe, non-attributive RF spectrum analysis.

The package intentionally reports only observable spectrum activity.  It does
not identify emitters, infer distance, or claim that an object is approaching.
"""

from .decision import (
    RF_FAMILY_EXPLANATIONS_RU,
    DataQuality,
    DecisionAlternative,
    DecisionEvidence,
    DecisionInputError,
    DecisionLifecycle,
    DecisionTransition,
    DecisionTransitionKind,
    DecisionUpdate,
    EvidenceStrength,
    RfDecision,
    RfDecisionEngine,
    RfFamily,
    SensorContribution,
    TemporalDecisionConfig,
)
from .detector import (
    TREND_LIMITATION,
    AnalysisResult,
    AssessmentState,
    AssessmentTrust,
    AttributionStatus,
    DetectorConfig,
    EventClass,
    FrameValidationError,
    LevelTrend,
    QualityFlag,
    RfEvent,
    RfEventDetector,
    RfEvidence,
    SignalAssessment,
    SignalAssessmentEvidence,
    SourceObservationMetadata,
    SpectrumAcquisitionMode,
    assessment_with_data_age,
    data_unreliable_assessment,
    no_data_assessment,
)
from .sensitivity import (
    DetectionSensitivity,
    DetectionSensitivityConfigs,
    configs_for_detection_sensitivity,
)

__all__ = [
    "RF_FAMILY_EXPLANATIONS_RU",
    "TREND_LIMITATION",
    "AnalysisResult",
    "AssessmentState",
    "AssessmentTrust",
    "AttributionStatus",
    "DataQuality",
    "DecisionAlternative",
    "DecisionEvidence",
    "DecisionInputError",
    "DecisionLifecycle",
    "DecisionTransition",
    "DecisionTransitionKind",
    "DecisionUpdate",
    "DetectionSensitivity",
    "DetectionSensitivityConfigs",
    "DetectorConfig",
    "EventClass",
    "EvidenceStrength",
    "FrameValidationError",
    "LevelTrend",
    "QualityFlag",
    "RfDecision",
    "RfDecisionEngine",
    "RfEvent",
    "RfEventDetector",
    "RfEvidence",
    "RfFamily",
    "SensorContribution",
    "SignalAssessment",
    "SignalAssessmentEvidence",
    "SourceObservationMetadata",
    "SpectrumAcquisitionMode",
    "TemporalDecisionConfig",
    "assessment_with_data_age",
    "configs_for_detection_sensitivity",
    "data_unreliable_assessment",
    "no_data_assessment",
]
